"""Repository and gateway interfaces the use cases depend on.

All are structural Protocols so infrastructure can satisfy them with
SQLAlchemy models without the application layer importing the ORM.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import datetime
from decimal import Decimal
from typing import Any, Protocol

from src.domain.cursor import Cursor
from src.domain.leads import LeadStage


class AuditWriter(Protocol):
    async def write(
        self,
        actor: str,
        action: str,
        entity: str,
        entity_id: uuid.UUID | None,
        diff: dict[str, Any] | None,
    ) -> None: ...


# ------------------------------------------------------------------ row shapes


class SiteRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def location(self) -> str | None: ...
    @property
    def budget_thb(self) -> Decimal | None: ...
    @property
    def created_at(self) -> datetime: ...


class ContractorRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def contact(self) -> str | None: ...
    @property
    def line_id(self) -> str | None: ...


class QuotationRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def site_id(self) -> uuid.UUID: ...
    @property
    def contractor_id(self) -> uuid.UUID: ...
    @property
    def category(self) -> str: ...
    @property
    def amount_thb(self) -> Decimal: ...
    @property
    def status(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...


class DrawRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def quotation_id(self) -> uuid.UUID: ...
    @property
    def seq(self) -> int: ...
    @property
    def amount_thb(self) -> Decimal: ...
    @property
    def status(self) -> str: ...
    @property
    def requested_at(self) -> datetime: ...
    @property
    def paid_at(self) -> datetime | None: ...


class SpendRow(Protocol):
    """One (site, category) aggregation row."""

    @property
    def site_id(self) -> uuid.UUID: ...
    @property
    def category(self) -> str: ...
    @property
    def quoted_thb(self) -> Decimal: ...
    @property
    def paid_thb(self) -> Decimal: ...
    @property
    def pending_thb(self) -> Decimal: ...


class LeadRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def locale(self) -> str | None: ...
    @property
    def intent_score(self) -> int: ...
    @property
    def stage(self) -> str: ...
    @property
    def first_seen_at(self) -> datetime: ...
    @property
    def last_activity_at(self) -> datetime | None: ...
    @property
    def created_at(self) -> datetime: ...


# ------------------------------------------------------------------ repositories


class RenovationRepository(Protocol):
    async def create_site(
        self, name: str, location: str | None, budget_thb: Decimal | None
    ) -> SiteRow: ...
    async def list_sites(self) -> Sequence[SiteRow]: ...
    async def get_site(self, site_id: uuid.UUID) -> SiteRow | None: ...
    async def create_contractor(
        self, name: str, contact: str | None, line_id: str | None
    ) -> ContractorRow: ...
    async def get_contractor(self, contractor_id: uuid.UUID) -> ContractorRow | None: ...
    async def create_quotation(
        self,
        site_id: uuid.UUID,
        contractor_id: uuid.UUID,
        category: str,
        amount_thb: Decimal,
        status: str,
    ) -> QuotationRow: ...
    async def get_quotation(self, quotation_id: uuid.UUID) -> QuotationRow | None: ...
    async def list_draws(self, quotation_id: uuid.UUID) -> Sequence[DrawRow]: ...
    async def create_draw(
        self, quotation_id: uuid.UUID, seq: int, amount_thb: Decimal
    ) -> DrawRow: ...
    async def get_draw(self, draw_id: uuid.UUID) -> DrawRow | None: ...
    async def mark_draw_paid(self, draw_id: uuid.UUID, paid_at: datetime) -> DrawRow: ...
    async def spend_rows(self) -> Sequence[SpendRow]: ...


class LeadRepository(Protocol):
    async def get(self, lead_id: uuid.UUID) -> LeadRow | None: ...
    async def list_page(
        self,
        *,
        stage: LeadStage | None,
        min_score: int | None,
        q: str | None,
        after: Cursor | None,
        limit: int,
    ) -> Sequence[LeadRow]: ...
    async def set_stage(
        self, lead_id: uuid.UUID, stage: LeadStage, activity_at: datetime
    ) -> LeadRow: ...
    async def add_event(
        self,
        lead_id: uuid.UUID,
        event_type: str,
        payload: dict[str, Any] | None,
        occurred_at: datetime,
    ) -> None: ...
