"""Repository and gateway interfaces the use cases depend on.

All are structural Protocols so infrastructure can satisfy them with
SQLAlchemy models without the application layer importing the ORM.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from datetime import date, datetime
from decimal import Decimal
from typing import Any, Protocol

from src.domain.cursor import Cursor
from src.domain.leads import LeadStage


class AuditWriter(Protocol):
    async def write(
        self,
        actor: str,
        action: str,
        entity: str,
        entity_id: uuid.UUID | None,
        diff: dict[str, Any] | None,
    ) -> None: ...


# ------------------------------------------------------------------ row shapes


class SiteRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def location(self) -> str | None: ...
    @property
    def budget_thb(self) -> Decimal | None: ...
    @property
    def created_at(self) -> datetime: ...


class ContractorRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def contact(self) -> str | None: ...
    @property
    def line_id(self) -> str | None: ...


class QuotationRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def site_id(self) -> uuid.UUID: ...
    @property
    def contractor_id(self) -> uuid.UUID: ...
    @property
    def category(self) -> str: ...
    @property
    def amount_thb(self) -> Decimal: ...
    @property
    def status(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...


class DrawRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def quotation_id(self) -> uuid.UUID: ...
    @property
    def seq(self) -> int: ...
    @property
    def amount_thb(self) -> Decimal: ...
    @property
    def status(self) -> str: ...
    @property
    def requested_at(self) -> datetime: ...
    @property
    def paid_at(self) -> datetime | None: ...


class SpendRow(Protocol):
    """One (site, category) aggregation row."""

    @property
    def site_id(self) -> uuid.UUID: ...
    @property
    def category(self) -> str: ...
    @property
    def quoted_thb(self) -> Decimal: ...
    @property
    def paid_thb(self) -> Decimal: ...
    @property
    def pending_thb(self) -> Decimal: ...


class DrawDisplayRow(Protocol):
    """A draw enriched with quotation/contractor/site context for display."""

    @property
    def id(self) -> uuid.UUID: ...
    @property
    def seq(self) -> int: ...
    @property
    def amount_thb(self) -> Decimal: ...
    @property
    def status(self) -> str: ...
    @property
    def requested_at(self) -> datetime: ...
    @property
    def paid_at(self) -> datetime | None: ...
    @property
    def quotation_id(self) -> uuid.UUID: ...
    @property
    def category(self) -> str: ...
    @property
    def contractor_name(self) -> str: ...
    @property
    def site_id(self) -> uuid.UUID: ...
    @property
    def site_name(self) -> str: ...


class MilestoneRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def site_id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def planned_date(self) -> date | None: ...
    @property
    def actual_date(self) -> date | None: ...
    @property
    def status(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...


class BankTransactionRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def occurred_at(self) -> datetime: ...
    @property
    def amount_thb(self) -> Decimal: ...
    @property
    def direction(self) -> str: ...
    @property
    def bank(self) -> str: ...
    @property
    def account_tail(self) -> str | None: ...
    @property
    def raw_text(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def matched_draw_id(self) -> uuid.UUID | None: ...
    @property
    def ambiguous_match(self) -> bool: ...
    @property
    def dedup_hash(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...


class ReportRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def kind(self) -> str: ...
    @property
    def period(self) -> str | None: ...
    @property
    def lang(self) -> str: ...
    @property
    def body(self) -> str | None: ...
    @property
    def sent_at(self) -> datetime | None: ...
    @property
    def created_at(self) -> datetime: ...


class DocumentRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def title(self) -> str: ...
    @property
    def mime(self) -> str: ...
    @property
    def storage_key(self) -> str: ...
    @property
    def lang(self) -> str | None: ...
    @property
    def ocr_done(self) -> bool: ...
    @property
    def meili_indexed(self) -> bool: ...
    @property
    def embedded(self) -> bool: ...
    @property
    def status(self) -> str: ...
    @property
    def error(self) -> str | None: ...
    @property
    def size_bytes(self) -> int | None: ...
    @property
    def source(self) -> str: ...
    @property
    def created_at(self) -> datetime: ...


class ChunkRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def document_id(self) -> uuid.UUID: ...
    @property
    def seq(self) -> int: ...
    @property
    def text(self) -> str: ...


class ChunkHydrationRow(Protocol):
    """A chunk joined with its document title, for search-result hydration."""

    @property
    def id(self) -> uuid.UUID: ...
    @property
    def document_id(self) -> uuid.UUID: ...
    @property
    def document_title(self) -> str: ...
    @property
    def seq(self) -> int: ...
    @property
    def text(self) -> str: ...


class MemoryRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def kind(self) -> str: ...
    @property
    def subject(self) -> str: ...
    @property
    def body(self) -> str: ...
    @property
    def importance(self) -> int: ...
    @property
    def embedding_point_id(self) -> str | None: ...
    @property
    def expires_at(self) -> datetime | None: ...
    @property
    def consolidated_into(self) -> uuid.UUID | None: ...
    @property
    def created_at(self) -> datetime: ...


class LeadRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def locale(self) -> str | None: ...
    @property
    def intent_score(self) -> int: ...
    @property
    def stage(self) -> str: ...
    @property
    def first_seen_at(self) -> datetime: ...
    @property
    def last_activity_at(self) -> datetime | None: ...
    @property
    def created_at(self) -> datetime: ...


# ---------------------------------------------------------- M3 competitor intel


class CompetitorRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def active(self) -> bool: ...


class SourceRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def url(self) -> str | None: ...
    @property
    def tos_policy(self) -> str: ...
    @property
    def rate_limit_per_hr(self) -> int: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def competitor_id(self) -> uuid.UUID | None: ...
    @property
    def last_fetched_at(self) -> datetime | None: ...
    @property
    def last_status(self) -> str | None: ...


class SourceDisplayRow(SourceRow, Protocol):
    """A source joined with its competitor's name (null-safe outer join)."""

    @property
    def competitor_name(self) -> str | None: ...


class SnapshotRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def competitor_id(self) -> uuid.UUID: ...
    @property
    def source_id(self) -> uuid.UUID | None: ...
    @property
    def captured_at(self) -> datetime: ...
    @property
    def content_hash(self) -> str: ...
    @property
    def storage_key(self) -> str: ...


class ChangeEventCreatedRow(Protocol):
    @property
    def id(self) -> uuid.UUID: ...
    @property
    def category(self) -> str: ...
    @property
    def severity(self) -> str: ...


class ChangeEventDisplayRow(Protocol):
    """A change event joined with its competitor's name, for feeds/reports."""

    @property
    def id(self) -> uuid.UUID: ...
    @property
    def competitor_id(self) -> uuid.UUID: ...
    @property
    def competitor_name(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def detected_at(self) -> datetime: ...


class CompetitorIntelRepository(Protocol):
    async def get_competitor(self, competitor_id: uuid.UUID) -> CompetitorRow | None: ...
    async def create_source(
        self,
        *,
        name: str,
        type: str,  # noqa: A002 - mirrors the column name
        url: str,
        competitor_id: uuid.UUID | None,
        rate_limit_per_hr: int,
        tos_policy: str,
        robots_ok: bool,
        enabled: bool,
    ) -> SourceRow: ...
    async def get_source(self, source_id: uuid.UUID) -> SourceRow | None: ...
    async def list_sources(
        self, competitor_id: uuid.UUID | None
    ) -> Sequence[SourceDisplayRow]: ...
    async def sweep_sources(
        self, competitor_id: uuid.UUID | None
    ) -> Sequence[SourceDisplayRow]:
        """Enabled competitor-linked sources of active competitors."""
        ...

    async def set_source_result(
        self, source_id: uuid.UUID, status: str, fetched_at: datetime | None
    ) -> None: ...
    async def latest_snapshot(
        self, competitor_id: uuid.UUID, source_id: uuid.UUID
    ) -> SnapshotRow | None: ...
    async def create_snapshot(
        self,
        *,
        competitor_id: uuid.UUID,
        source_id: uuid.UUID,
        content_hash: str,
        storage_key: str,
    ) -> SnapshotRow: ...
    async def create_change_event(
        self,
        *,
        competitor_id: uuid.UUID,
        snapshot_id: uuid.UUID | None,
        category: str,
        summary: str,
        severity: str,
    ) -> ChangeEventCreatedRow: ...
    async def change_events_since(
        self, since: datetime
    ) -> Sequence[ChangeEventDisplayRow]: ...
    async def create_report(
        self, *, kind: str, period: str, lang: str, body: str, sent_at: datetime | None
    ) -> ReportRow: ...


# ------------------------------------------------------------------ repositories


class RenovationRepository(Protocol):
    async def create_site(
        self, name: str, location: str | None, budget_thb: Decimal | None
    ) -> SiteRow: ...
    async def list_sites(self) -> Sequence[SiteRow]: ...
    async def get_site(self, site_id: uuid.UUID) -> SiteRow | None: ...
    async def create_contractor(
        self, name: str, contact: str | None, line_id: str | None
    ) -> ContractorRow: ...
    async def get_contractor(self, contractor_id: uuid.UUID) -> ContractorRow | None: ...
    async def create_quotation(
        self,
        site_id: uuid.UUID,
        contractor_id: uuid.UUID,
        category: str,
        amount_thb: Decimal,
        status: str,
    ) -> QuotationRow: ...
    async def get_quotation(self, quotation_id: uuid.UUID) -> QuotationRow | None: ...
    async def list_draws(self, quotation_id: uuid.UUID) -> Sequence[DrawRow]: ...
    async def create_draw(
        self, quotation_id: uuid.UUID, seq: int, amount_thb: Decimal
    ) -> DrawRow: ...
    async def get_draw(self, draw_id: uuid.UUID) -> DrawRow | None: ...
    async def mark_draw_paid(self, draw_id: uuid.UUID, paid_at: datetime) -> DrawRow: ...
    async def spend_rows(self) -> Sequence[SpendRow]: ...
    async def list_quotations(self, site_id: uuid.UUID) -> Sequence[QuotationRow]: ...
    async def list_draws_display(
        self, site_id: uuid.UUID | None, status: str | None
    ) -> Sequence[DrawDisplayRow]: ...
    async def list_milestones(self, site_id: uuid.UUID) -> Sequence[MilestoneRow]: ...
    async def get_milestone(self, milestone_id: uuid.UUID) -> MilestoneRow | None: ...
    async def create_milestone(
        self, site_id: uuid.UUID, name: str, planned_date: date | None
    ) -> MilestoneRow: ...
    async def update_milestone(
        self, milestone_id: uuid.UUID, changes: dict[str, Any]
    ) -> MilestoneRow: ...


class BankTransactionRepository(Protocol):
    async def get(self, tx_id: uuid.UUID) -> BankTransactionRow | None: ...
    async def get_by_dedup_hash(self, dedup_hash: str) -> BankTransactionRow | None: ...
    async def create(
        self,
        *,
        occurred_at: datetime,
        amount_thb: Decimal,
        direction: str,
        bank: str,
        account_tail: str | None,
        raw_text: str,
        source: str,
        status: str,
        matched_draw_id: uuid.UUID | None,
        ambiguous_match: bool,
        dedup_hash: str,
    ) -> BankTransactionRow: ...
    async def list(self, status: str | None, limit: int) -> Sequence[BankTransactionRow]: ...
    async def set_match(
        self,
        tx_id: uuid.UUID,
        *,
        status: str,
        matched_draw_id: uuid.UUID | None,
        ambiguous_match: bool,
    ) -> BankTransactionRow: ...
    async def set_status(self, tx_id: uuid.UUID, status: str) -> BankTransactionRow: ...
    async def list_pending_draws(self) -> Sequence[DrawRow]: ...
    async def get_draw(self, draw_id: uuid.UUID) -> DrawRow | None: ...


class KnowledgeBaseRepository(Protocol):
    async def create_document(
        self,
        *,
        id: uuid.UUID,
        title: str,
        mime: str,
        storage_key: str,
        lang: str | None,
        size_bytes: int,
        source: str,
    ) -> DocumentRow: ...
    async def get_document(self, document_id: uuid.UUID) -> DocumentRow | None: ...
    async def list_documents(self, status: str | None, limit: int) -> Sequence[DocumentRow]: ...
    async def update_document(
        self, document_id: uuid.UUID, changes: dict[str, Any]
    ) -> DocumentRow: ...
    async def replace_chunks(
        self, document_id: uuid.UUID, chunks: Sequence[tuple[int, str]]
    ) -> Sequence[ChunkRow]: ...
    async def set_chunk_point_ids(self, chunk_ids: Sequence[uuid.UUID]) -> None: ...
    async def chunk_count(self, document_id: uuid.UUID) -> int: ...
    async def get_chunks_with_titles(
        self, chunk_ids: Sequence[uuid.UUID]
    ) -> Sequence[ChunkHydrationRow]: ...


class MemoryRepository(Protocol):
    async def create(
        self,
        *,
        kind: str,
        subject: str,
        body: str,
        importance: int,
        expires_at: datetime | None,
        source_run_id: uuid.UUID | None,
    ) -> MemoryRow: ...
    async def set_embedding_point(self, memory_id: uuid.UUID, point_id: str) -> MemoryRow: ...
    async def search_text(
        self, q: str, kind: str | None, limit: int, now: datetime
    ) -> Sequence[MemoryRow]: ...
    async def get_active_many(
        self, memory_ids: Sequence[uuid.UUID], now: datetime
    ) -> Sequence[MemoryRow]: ...
    async def list_active(self, now: datetime) -> Sequence[MemoryRow]: ...
    async def list_expired(self, now: datetime) -> Sequence[MemoryRow]: ...
    async def mark_consolidated(
        self, memory_ids: Sequence[uuid.UUID], survivor_id: uuid.UUID
    ) -> None: ...
    async def delete_many(self, memory_ids: Sequence[uuid.UUID]) -> None: ...


class LeadRepository(Protocol):
    async def get(self, lead_id: uuid.UUID) -> LeadRow | None: ...
    async def list_page(
        self,
        *,
        stage: LeadStage | None,
        min_score: int | None,
        q: str | None,
        after: Cursor | None,
        limit: int,
    ) -> Sequence[LeadRow]: ...
    async def set_stage(
        self, lead_id: uuid.UUID, stage: LeadStage, activity_at: datetime
    ) -> LeadRow: ...
    async def add_event(
        self,
        lead_id: uuid.UUID,
        event_type: str,
        payload: dict[str, Any] | None,
        occurred_at: datetime,
    ) -> None: ...
